<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="course/css/bootstrap.css">
    <link rel="stylesheet" href="course/css/bootstrap.min.css">


</head>


<body>
<nav class="navbar navbar-default">

    <div class="container">

            <div class="navbar-header">
                <a class="navbar-brand" href="/" >Home page</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li> <a class="nav-item btn" href="/?page=books">Books</a></li>
                    <li><a class="nav-item btn" href="/?page=contact">Contacts</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a class=" btn btn-secondary" href="/?page=cart"><span class="glyphicon glyphicon-shopping-cart size_cart_icon" ></span></a></li>
                </ul>
            </div>


    </div>
</nav>






    <div class="main_padding">

        <?=$content?>
        <br>
        <br>


    </div>

    <div class="text-center panel-footer footer">
        <span >mini site &copy; 2017</span>
    </div>

</body>
</html>