<h1 class="text-center">Books<span class="glyphicon glyphicon-book size_icon"></span></h1>




<div class="panel-group" >
<?php foreach ( $books as $book) : ?>

    <div class="panel panel-info">

        <div class="panel-heading">
            <div class="text-primary float-left">
                <span>Code:&#160</span> <?=$book['id']?>
            </div>
            <div class="text-right " >
                $<?=$book['price']?>
            </div>
        </div>

        <div class="panel-body">
            <h3><?=$book['title']?></h3>
            <i class="float-left">Author:&#160&#160</i><h4><?=$book['author']?></h4>

        </div>
        <div class="panel-footer text-right">
            <a href="/?page=books&amp;action=show&amp;id=<?=$book['id']?>" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-eye-open " ></span>&#160Show</a>
            <a href="/?page=cart&amp;action=add&amp;id=<?=$book['id']?>" class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-shopping-cart " ></span>&#160Add to cart</a>

        </div>




    </div>


<?php endforeach; ?>
</div>