<h1 class="text-center">Contact&#160<span class="glyphicon glyphicon-comment size_icon" ></span></h1>




<div class="row"></div>
    <div class="col-md-3"></div>
        <div class="bd-my-callout_contact_form col-md-6" >

            <form method="post">
                <div class=" form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input  class="form-control" type="text" name="email" placeholder="Enter email"/>
                </div>
                <div class="form-group">
                    <label >Phone</label>
                    <input class="form-control" type="text" name="phone" placeholder="Enter our phone"/>
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email and phone with anyone else.</small>
                </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Message</label>
                        <textarea class="form-control" name="message" rows="3" style="resize:vertical" placeholder="Message..."></textarea>
                    </div>
                <div class="form-group ">
                    <input class="btn btn-primary float-rigth" type="submit" value="&#160&#160&#160Send&#160&#160&#160"/>
                </div>
            </form>

    </div>
    <div class="col-md-3"></div>
</div>